CC			= gcc
CFLAGS	= --std=iso9899:1990 -I../utils -Wall -Wpedantic

BIN = solution

$(BIN): %: obj/%.o obj/test.o
	$(CC) $(CFLAGS) -o $@ $^

obj/%.o: %.c
	@mkdir -p obj/
	$(CC) $(CFLAGS) -c -o $@ $<

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(BIN) obj/*.o
