
name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: build website 
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' 
    - run: npm ci
    - run: npm run build
    - name: deploy to server 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        rm: true
        source: "_site/*"
        target: "/var/www/jakobmaier.at/stuff"
        strip_components: 1
        
       
